### ISSUE TITLE
How to integrate with IDEs?

### ISSUE THREAD

**Issue by d9k** [evolution-gaming/tsc-silent#7]
How to integrate with popular IDEs to suppress errors, for example IntelliJ IDEA/PhpStorm/WebStorm, Atom, VS Code?

IntellJ settings page:
![Screenshot from 2019-10-17 20-27-23](https://user-images.githubusercontent.com/7331988/67033251-fcd9f980-f11d-11e9-887e-3925152eeb95.png)

**Comment by pablobirukov** [comment]
Thanks for the interest, but there is no way to integrate the lib with IDE and no intention to add this functionality.

I explained our motivation [in my blog in more detail](https://birukov.me/blog/all/tsc-silent.html).
