### ISSUE TITLE
Suppress all?

### ISSUE THREAD

**Issue by goldingdamien** [evolution-gaming/tsc-silent#9]
Is there any way to suppress all errors?
I am trying to output a declaration file on a typescript project that still has many errors. Is this possible?

Regards.

**Comment by pablobirukov** [comment]
I've updated [README](https://github.com/evolution-gaming/tsc-silent/blob/master/README.md#--suppress) with the example that ignores all errors.

But TypeScript itself generates output even when there are compiler errors. The exception is [--noEmitOnError](https://www.typescriptlang.org/docs/handbook/compiler-options.html) flag turned on.
